spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.119:3306/dbfilm?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  output:
    ansi:
      enabled: detect
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    timeout: 0

#debug: true

#  cache:
#    properties:
#      hibernate :
#       generate_statistics: true
#       cache :
#        use_second_level_cache: true
#        use_query_cache: true
#        region:
#          factoryClass: org.hibernate.cache.ehcache.EhCacheRegionFactory
#      javax:
#        persistence:
#          sharedCache:
#            mode: ENABLE_SELECTIVE